blank_issues_enabled: true

contact_links:
  - name: ğŸ“šä½¿ç”¨æ–‡æ¡£
    url: https://smartboot.tech/smart-servlet/
    about: smart-servlet in Actionï¼Œç®€å•ã€é«˜æ•ˆã€å›½äº§åŒ–

template_order:
  - license_apply.yml
  - license_inquiry.yml
  - enterprise_support.yml
  - opensource_bug.yml

